apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-api-gateway
  labels:
    app: petclinic-api-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: petclinic-api-gateway
  template:
    metadata:
      labels:
        app: petclinic-api-gateway
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.image.repository }}/spring-petclinic-api-gateway:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}